name: Keep Codespace Active

on:
  schedule:
    - cron: '0 * * * *'  # This runs every hour

jobs:
  run-codespace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run some task
        run: echo "Keeping Codespace Active"
